import java.io.IOException;
import java.util.*;
import org.apache.hadoop.io.IntWritable; 
import org.apache.hadoop.io.NullWritable;
import org.apache.hadoop.io.LongWritable; 
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Mapper;

public class Clean2Mapper 
    extends Mapper<LongWritable, Text, Text, Text> {

    // Since the counties were provided in numeric form, we must convert them to their corresponding strings
    public static String [][] countiesList = {{"autauga", "baldwin", "barbour", "bibb", "blount", "bullock", "butler", "calhoun", "chambers", "cherokee", "chilton", "choctaw", "clarke", "clay", "cleburne", "coffee", "colbert", "conecuh", "coosa", "covington", "crenshaw", "cullman", "dale", "dallas", "dekalb", "elmore", "escambia", "etowah", "fayette", "franklin", "geneva", "greene", "hale", "henry", "houston", "jackson", "jefferson", "lamar", "lauderdale", "lawrence", "lee", "limestone", "lowndes", "macon", "madison", "marengo", "marion", "marshall", "mobile", "monroe", "montgomery", "morgan", "perry", "pickens", "pike", "randolph", "russell", "st. clair", "shelby", "sumter", "talladega", "tallapoosa", "tuscaloosa", "walker", "washington", "wilcox", "winston"},
            {"apache", "cochise", "coconino", "gila", "graham", "greenlee", "la paz", "maricopa", "mohave", "navajo", "pima", "pinal", "santa cruz", "yavapai", "yuma"},
            {"arkansas", "ashley", "baxter", "benton", "boone", "bradley", "calhoun", "carroll", "chicot", "clark", "clay", "cleburne", "cleveland", "columbia", "conway", "craighead", "crawford", "crittenden", "cross", "dallas", "desha", "drew", "faulkner", "franklin", "fulton", "garland", "grant", "greene", "hempstead", "hot spring", "howard", "independence", "izard", "jackson", "jefferson", "johnson", "lafayette", "lawrence", "lee", "lincoln", "little river", "logan", "lonoke", "madison", "marion", "miller", "mississippi", "monroe", "montgomery", "nevada", "newton", "ouachita", "perry", "phillips", "pike", "poinsett", "polk", "pope", "prairie", "pulaski", "randolph", "st. francis", "saline", "scott", "searcy", "sebastian", "sevier", "sharp", "stone", "union", "van buren", "washington", "white", "woodruff", "yell"},
            {"alameda", "alpine", "amador", "butte", "calaveras", "colusa", "contra costa", "del norte", "el dorado", "fresno", "glenn", "humboldt", "imperial", "inyo", "kern", "kings", "lake", "lassen", "los angeles", "madera", "marin", "mariposa", "mendocino", "merced", "modoc", "mono", "monterey", "napa", "nevada", "orange", "placer", "plumas", "riverside", "sacramento", "san benito", "san bernardino", "san diego", "san francisco", "san joaquin", "san luis obispo", "san mateo", "santa barbara", "santa clara", "santa cruz", "shasta", "sierra", "siskiyou", "solano", "sonoma", "stanislaus", "sutter", "tehama", "trinity", "tulare", "tuolumne", "ventura", "yolo", "yuba"},
            {"adams", "alamosa", "arapahoe", "archuleta", "baca", "bent", "boulder", "chaffee", "cheyenne", "clear creek", "conejos", "costilla", "crowley", "custer", "delta", "denver", "dolores", "douglas", "eagle", "elbert", "el paso", "fremont", "garfield", "gilpin", "grand", "gunnison", "hinsdale", "huerfano", "jackson", "jefferson", "kiowa", "kit carson", "lake", "la plata", "larimer", "las animas", "lincoln", "logan", "mesa", "mineral", "moffat", "montezuma", "montrose", "morgan", "otero", "ouray", "park", "phillips", "pitkin", "prowers", "pueblo", "rio blanco", "rio grande", "routt", "saguache", "san juan", "san miguel", "sedgwick", "summit", "teller", "washington", "weld", "yuma"},
            {"fairfield", "hartford", "litchfield", "middlesex", "new haven", "new london", "tolland", "windham"},
            {"kent", "new castle", "sussex"},
            {"district of columbia"},
            {"alachua", "baker", "bay", "bradford", "brevard", "broward", "calhoun", "charlotte", "citrus", "clay", "collier", "columbia", "dade", "desoto", "dixie", "duval", "escambia", "flagler", "franklin", "gadsden", "gilchrist", "glades", "gulf", "hamilton", "hardee", "hendry", "hernando", "highlands", "hillsborough", "holmes", "indian river", "jackson", "jefferson", "lafayette", "lake", "lee", "leon", "levy", "liberty", "madison", "manatee", "marion", "martin", "monroe", "nassau", "okaloosa", "okeechobee", "orange", "osceola", "palm beach", "pasco", "pinellas", "polk", "putnam", "st. johns", "st. lucie", "santa rosa", "sarasota", "seminole", "sumter", "suwannee", "taylor", "union", "volusia", "wakulla", "walton", "washington"},
            {"appling", "atkinson", "bacon", "baker", "baldwin", "banks", "barrow", "bartow", "ben hill", "berrien", "bibb", "bleckley", "brantley", "brooks", "bryan", "bulloch", "burke", "butts", "calhoun", "camden", "candler", "carroll", "catoosa", "charlton", "chatham", "chattahoochee", "chattooga", "cherokee", "clarke", "clay", "clayton", "clinch", "cobb", "coffee", "colquitt", "columbia", "cook", "coweta", "crawford", "crisp", "dade", "dawson", "decatur", "dekalb", "dodge", "dooly", "dougherty", "douglas", "early", "echols", "effingham", "elbert", "emanuel", "evans", "fannin", "fayette", "floyd", "forsyth", "franklin", "fulton", "gilmer", "glascock", "glynn", "gordon", "grady", "greene", "gwinnett", "habersham", "hall", "hancock", "haralson", "harris", "hart", "heard", "henry", "houston", "irwin", "jackson", "jasper", "jeff davis", "jefferson", "jenkins", "johnson", "jones", "lamar", "lanier", "laurens", "lee", "liberty", "lincoln", "long", "lowndes", "lumpkin", "mcduffie", "mcintosh", "macon", "madison", "marion", "meriwether", "miller", "mitchell", "monroe", "montgomery", "morgan", "murray", "muscogee", "newton", "oconee", "oglethorpe", "paulding", "peach", "pickens", "pierce", "pike", "polk", "pulaski", "putnam", "quitman", "rabun", "randolph", "richmond", "rockdale", "schley", "screven", "seminole", "spalding", "stephens", "stewart", "sumter", "talbot", "taliaferro", "tattnall", "taylor", "telfair", "terrell", "thomas", "tift", "toombs", "towns", "treutlen", "troup", "turner", "twiggs", "union", "upson", "walker", "walton", "ware", "warren", "washington", "wayne", "webster", "wheeler", "white", "whitfield", "wilcox", "wilkes", "wilkinson", "worth"},
            {"ada", "adams", "bannock", "bear lake", "benewah", "bingham", "blaine", "boise", "bonner", "bonneville", "boundary", "butte", "camas", "canyon", "caribou", "cassia", "clark", "clearwater", "custer", "elmore", "franklin", "fremont", "gem", "gooding", "idaho", "jefferson", "jerome", "kootenai", "latah", "lemhi", "lewis", "lincoln", "madison", "minidoka", "nez perce", "oneida", "owyhee", "payette", "power", "shoshone", "teton", "twin falls", "valley", "washington"},
            {"adams", "alexander", "bond", "boone", "brown", "bureau", "calhoun", "carroll", "cass", "champaign", "christian", "clark", "clay", "clinton", "coles", "cook", "crawford", "cumberland", "dekalb", "de witt", "douglas", "dupage", "edgar", "edwards", "effingham", "fayette", "ford", "franklin", "fulton", "gallatin", "greene", "grundy", "hamilton", "hancock", "hardin", "henderson", "henry", "iroquois", "jackson", "jasper", "jefferson", "jersey", "jo daviess", "johnson", "kane", "kankakee", "kendall", "knox", "lake", "la salle", "lawrence", "lee", "livingston", "logan", "mcdonough", "mchenry", "mclean", "macon", "macoupin", "madison", "marion", "marshall", "mason", "massac", "menard", "mercer", "monroe", "montgomery", "morgan", "moultrie", "ogle", "peoria", "perry", "piatt", "pike", "pope", "pulaski", "putnam", "randolph", "richland", "rock island", "st. clair", "saline", "sangamon", "schuyler", "scott", "shelby", "stark", "stephenson", "tazewell", "union", "vermilion", "wabash", "warren", "washington", "wayne", "white", "whiteside", "will", "williamson", "winnebago", "woodford"},
            {"adams", "allen", "bartholomew", "benton", "blackford", "boone", "brown", "carroll", "cass", "clark", "clay", "clinton", "crawford", "daviess", "dearborn", "decatur", "de kalb", "delaware", "dubois", "elkhart", "fayette", "floyd", "fountain", "franklin", "fulton", "gibson", "grant", "greene", "hamilton", "hancock", "harrison", "hendricks", "henry", "howard", "huntington", "jackson", "jasper", "jay", "jefferson", "jennings", "johnson", "knox", "kosciusko", "lagrange", "lake", "la porte", "lawrence", "madison", "marion", "marshall", "martin", "miami", "monroe", "montgomery", "morgan", "newton", "noble", "ohio", "orange", "owen", "parke", "perry", "pike", "porter", "posey", "pulaski", "putnam", "randolph", "ripley", "rush", "st. joseph", "scott", "shelby", "spencer", "starke", "steuben", "sullivan", "switzerland", "tippecanoe", "tipton", "union", "vanderburgh", "vermillion", "vigo", "wabash", "warren", "warrick", "washington", "wayne", "wells", "white", "whitley"},
            {"adair", "adams", "allamakee", "appanoose", "audubon", "benton", "black hawk", "boone", "bremer", "buchanan", "buena vista", "butler", "calhoun", "carroll", "cass", "cedar", "cerro gordo", "cherokee", "chickasaw", "clarke", "clay", "clayton", "clinton", "crawford", "dallas", "davis", "decatur", "delaware", "des moines", "dickinson", "dubuque", "emmet", "fayette", "floyd", "franklin", "fremont", "greene", "grundy", "guthrie", "hamilton", "hancock", "hardin", "harrison", "henry", "howard", "humboldt", "ida", "iowa", "jackson", "jasper", "jefferson", "johnson", "jones", "keokuk", "kossuth", "lee", "linn", "louisa", "lucas", "lyon", "madison", "mahaska", "marion", "marshall", "mills", "mitchell", "monona", "monroe", "montgomery", "muscatine", "o", "osceola", "page", "palo alto", "plymouth", "pocahontas", "polk", "pottawattamie", "poweshiek", "ringgold", "sac", "scott", "shelby", "sioux", "story", "tama", "taylor", "union", "van buren", "wapello", "warren", "washington", "wayne", "webster", "winnebago", "winneshiek", "woodbury", "worth", "wright"},
            {"allen", "anderson", "atchison", "barber", "barton", "bourbon", "brown", "butler", "chase", "chautauqua", "cherokee", "cheyenne", "clark", "clay", "cloud", "coffey", "comanche", "cowley", "crawford", "decatur", "dickinson", "doniphan", "douglas", "edwards", "elk", "ellis", "ellsworth", "finney", "ford", "franklin", "geary", "gove", "graham", "grant", "gray", "greeley", "greenwood", "hamilton", "harper", "harvey", "haskell", "hodgeman", "jackson", "jefferson", "jewell", "johnson", "kearny", "kingman", "kiowa", "labette", "lane", "leavenworth", "lincoln", "linn", "logan", "lyon", "mcpherson", "marion", "marshall", "meade", "miami", "mitchell", "montgomery", "morris", "morton", "nemaha", "neosho", "ness", "norton", "osage", "osborne", "ottawa", "pawnee", "phillips", "pottawatomie", "pratt", "rawlins", "reno", "republic", "rice", "riley", "rooks", "rush", "russell", "saline", "scott", "sedgwick", "seward", "shawnee", "sheridan", "sherman", "smith", "stafford", "stanton", "stevens", "sumner", "thomas", "trego", "wabaunsee", "wallace", "washington", "wichita", "wilson", "woodson", "wyandotte"},
            {"adair", "allen", "anderson", "ballard", "barren", "bath", "bell", "boone", "bourbon", "boyd", "boyle", "bracken", "breathitt", "breckinridge", "bullitt", "butler", "caldwell", "calloway", "campbell", "carlisle", "carroll", "carter", "casey", "christian", "clark", "clay", "clinton", "crittenden", "cumberland", "daviess", "edmonson", "elliott", "estill", "fayette", "fleming", "floyd", "franklin", "fulton", "gallatin", "garrard", "grant", "graves", "grayson", "green", "greenup", "hancock", "hardin", "harlan", "harrison", "hart", "henderson", "henry", "hickman", "hopkins", "jackson", "jefferson", "jessamine", "johnson", "kenton", "knott", "knox", "larue", "laurel", "lawrence", "lee", "leslie", "letcher", "lewis", "lincoln", "livingston", "logan", "lyon", "mccracken", "mccreary", "mclean", "madison", "magoffin", "marion", "marshall", "martin", "mason", "meade", "menifee", "mercer", "metcalfe", "monroe", "montgomery", "morgan", "muhlenberg", "nelson", "nicholas", "ohio", "oldham", "owen", "owsley", "pendleton", "perry", "pike", "powell", "pulaski", "robertson", "rockcastle", "rowan", "russell", "scott", "shelby", "simpson", "spencer", "taylor", "todd", "trigg", "trimble", "union", "warren", "washington", "wayne", "webster", "whitley", "wolfe", "woodford"},
            {"acadia parish", "allen parish", "ascension parish", "assumption parish", "avoyelles parish", "beauregard parish", "bienville parish", "bossier parish", "caddo parish", "calcasieu parish", "caldwell parish", "cameron parish", "catahoula parish", "claiborne parish", "concordia parish", "de soto parish", "east baton rouge parish", "east carroll parish", "east feliciana parish", "evangeline parish", "franklin parish", "grant parish", "iberia parish", "iberville parish", "jackson parish", "jefferson parish", "jefferson davis parish", "lafayette parish", "lafourche parish", "la salle parish", "lincoln parish", "livingston parish", "madison parish", "morehouse parish", "natchitoches parish", "orleans parish", "ouachita parish", "plaquemines parish", "pointe coupee parish", "rapides parish", "red river parish", "richland parish", "sabine parish", "st. bernard parish", "st. charles parish", "st. helena parish", "st. james parish", "st. john the baptist parish", "st. landry parish", "st. martin parish", "st. mary parish", "st. tammany parish", "tangipahoa parish", "tensas parish", "terrebonne parish", "union parish", "vermilion parish", "vernon parish", "washington parish", "webster parish", "west baton rouge parish", "west carroll parish", "west feliciana parish", "winn parish"},
            {"androscoggin", "aroostook", "cumberland", "franklin", "hancock", "kennebec", "knox", "lincoln", "oxford", "penobscot", "piscataquis", "sagadahoc", "somerset", "waldo", "washington", "york"},
            {"allegany", "anne arundel", "baltimore", "calvert", "caroline", "carroll", "cecil", "charles", "dorchester", "frederick", "garrett", "harford", "howard", "kent", "montgomery", "prince george", "queen anne", "st. mary", "somerset", "talbot", "washington", "wicomico", "worcester", "baltimore city"},
            {"barnstable", "berkshire", "bristol", "dukes", "essex", "franklin", "hampden", "hampshire", "middlesex", "nantucket", "norfolk", "plymouth", "suffolk", "worcester"},
            {"alcona", "alger", "allegan", "alpena", "antrim", "arenac", "baraga", "barry", "bay", "benzie", "berrien", "branch", "calhoun", "cass", "charlevoix", "cheboygan", "chippewa", "clare", "clinton", "crawford", "delta", "dickinson", "eaton", "emmet", "genesee", "gladwin", "gogebic", "grand traverse", "gratiot", "hillsdale", "houghton", "huron", "ingham", "ionia", "iosco", "iron", "isabella", "jackson", "kalamazoo", "kalkaska", "kent", "keweenaw", "lake", "lapeer", "leelanau", "lenawee", "livingston", "luce", "mackinac", "macomb", "manistee", "marquette", "mason", "mecosta", "menominee", "midland", "missaukee", "monroe", "montcalm", "montmorency", "muskegon", "newaygo", "oakland", "oceana", "ogemaw", "ontonagon", "osceola", "oscoda", "otsego", "ottawa", "presque isle", "roscommon", "saginaw", "st. clair", "st. joseph", "sanilac", "schoolcraft", "shiawassee", "tuscola", "van buren", "washtenaw", "wayne", "wexford"},
            {"aitkin", "anoka", "becker", "beltrami", "benton", "big stone", "blue earth", "brown", "carlton", "carver", "cass", "chippewa", "chisago", "clay", "clearwater", "cook", "cottonwood", "crow wing", "dakota", "dodge", "douglas", "faribault", "fillmore", "freeborn", "goodhue", "grant", "hennepin", "houston", "hubbard", "isanti", "itasca", "jackson", "kanabec", "kandiyohi", "kittson", "koochiching", "lac qui parle", "lake", "lake of the woods", "le sueur", "lincoln", "lyon", "mcleod", "mahnomen", "marshall", "martin", "meeker", "mille lacs", "morrison", "mower", "murray", "nicollet", "nobles", "norman", "olmsted", "otter tail", "pennington", "pine", "pipestone", "polk", "pope", "ramsey", "red lake", "redwood", "renville", "rice", "rock", "roseau", "st. louis", "scott", "sherburne", "sibley", "stearns", "steele", "stevens", "swift", "todd", "traverse", "wabasha", "wadena", "waseca", "washington", "watonwan", "wilkin", "winona", "wright", "yellow medicine"},
            {"adams", "alcorn", "amite", "attala", "benton", "bolivar", "calhoun", "carroll", "chickasaw", "choctaw", "claiborne", "clarke", "clay", "coahoma", "copiah", "covington", "desoto", "forrest", "franklin", "george", "greene", "grenada", "hancock", "harrison", "hinds", "holmes", "humphreys", "issaquena", "itawamba", "jackson", "jasper", "jefferson", "jefferson davis", "jones", "kemper", "lafayette", "lamar", "lauderdale", "lawrence", "leake", "lee", "leflore", "lincoln", "lowndes", "madison", "marion", "marshall", "monroe", "montgomery", "neshoba", "newton", "noxubee", "oktibbeha", "panola", "pearl river", "perry", "pike", "pontotoc", "prentiss", "quitman", "rankin", "scott", "sharkey", "simpson", "smith", "stone", "sunflower", "tallahatchie", "tate", "tippah", "tishomingo", "tunica", "union", "walthall", "warren", "washington", "wayne", "webster", "wilkinson", "winston", "yalobusha", "yazoo"},
            {"adair", "andrew", "atchison", "audrain", "barry", "barton", "bates", "benton", "bollinger", "boone", "buchanan", "butler", "caldwell", "callaway", "camden", "cape girardeau", "carroll", "carter", "cass", "cedar", "chariton", "christian", "clark", "clay", "clinton", "cole", "cooper", "crawford", "dade", "dallas", "daviess", "dekalb", "dent", "douglas", "dunklin", "franklin", "gasconade", "gentry", "greene", "grundy", "harrison", "henry", "hickory", "holt", "howard", "howell", "iron", "jackson", "jasper", "jefferson", "johnson", "knox", "laclede", "lafayette", "lawrence", "lewis", "lincoln", "linn", "livingston", "mcdonald", "macon", "madison", "maries", "marion", "mercer", "miller", "mississippi", "moniteau", "monroe", "montgomery", "morgan", "new madrid", "newton", "nodaway", "oregon", "osage", "ozark", "pemiscot", "perry", "pettis", "phelps", "pike", "platte", "polk", "pulaski", "putnam", "ralls", "randolph", "ray", "reynolds", "ripley", "st. charles", "st. clair", "ste. genevieve", "st. francois", "st. louis", "saline", "schuyler", "scotland", "scott", "shannon", "shelby", "stoddard", "stone", "sullivan", "taney", "texas", "vernon", "warren", "washington", "wayne", "webster", "worth", "wright", "st. louis city"},
            {"beaverhead", "big horn", "blaine", "broadwater", "carbon", "carter", "cascade", "chouteau", "custer", "daniels", "dawson", "deer lodge", "fallon", "fergus", "flathead", "gallatin", "garfield", "glacier", "golden valley", "granite", "hill", "jefferson", "judith basin", "lake", "lewis and clark", "liberty", "lincoln", "mccone", "madison", "meagher", "mineral", "missoula", "musselshell", "park", "petroleum", "phillips", "pondera", "powder river", "powell", "prairie", "ravalli", "richland", "roosevelt", "rosebud", "sanders", "sheridan", "silver bow", "stillwater", "sweet grass", "teton", "toole", "treasure", "valley", "wheatland", "wibaux", "yellowstone", "yellowstone national park"},
            {"adams", "antelope", "arthur", "banner", "blaine", "boone", "box butte", "boyd", "brown", "buffalo", "burt", "butler", "cass", "cedar", "chase", "cherry", "cheyenne", "clay", "colfax", "cuming", "custer", "dakota", "dawes", "dawson", "deuel", "dixon", "dodge", "douglas", "dundy", "fillmore", "franklin", "frontier", "furnas", "gage", "garden", "garfield", "gosper", "grant", "greeley", "hall", "hamilton", "harlan", "hayes", "hitchcock", "holt", "hooker", "howard", "jefferson", "johnson", "kearney", "keith", "keya paha", "kimball", "knox", "lancaster", "lincoln", "logan", "loup", "mcpherson", "madison", "merrick", "morrill", "nance", "nemaha", "nuckolls", "otoe", "pawnee", "perkins", "phelps", "pierce", "platte", "polk", "red willow", "richardson", "rock", "saline", "sarpy", "saunders", "scotts bluff", "seward", "sheridan", "sherman", "sioux", "stanton", "thayer", "thomas", "thurston", "valley", "washington", "wayne", "webster", "wheeler", "york"},
            {"churchill", "clark", "douglas", "elko", "esmeralda", "eureka", "humboldt", "lander", "lincoln", "lyon", "mineral", "nye", "pershing", "storey", "washoe", "white pine", "carson city"},
            {"belknap", "carroll", "cheshire", "coos", "grafton", "hillsborough", "merrimack", "rockingham", "strafford", "sullivan"},
            {"atlantic", "bergen", "burlington", "camden", "cape may", "cumberland", "essex", "gloucester", "hudson", "hunterdon", "mercer", "middlesex", "monmouth", "morris", "ocean", "passaic", "salem", "somerset", "sussex", "union", "warren"},
            {"bernalillo", "catron", "chaves", "cibola", "colfax", "curry", "debaca", "dona ana", "eddy", "grant", "guadalupe", "harding", "hidalgo", "lea", "lincoln", "los alamos", "luna", "mckinley", "mora", "otero", "quay", "rio arriba", "roosevelt", "sandoval", "san juan", "san miguel", "santa fe", "sierra", "socorro", "taos", "torrance", "union", "valencia"},
            {"albany", "allegany", "bronx", "broome", "cattaraugus", "cayuga", "chautauqua", "chemung", "chenango", "clinton", "columbia", "cortland", "delaware", "dutchess", "erie", "essex", "franklin", "fulton", "genesee", "greene", "hamilton", "herkimer", "jefferson", "kings", "lewis", "livingston", "madison", "monroe", "montgomery", "nassau", "new york", "niagara", "oneida", "onondaga", "ontario", "orange", "orleans", "oswego", "otsego", "putnam", "queens", "rensselaer", "richmond", "rockland", "st. lawrence", "saratoga", "schenectady", "schoharie", "schuyler", "seneca", "steuben", "suffolk", "sullivan", "tioga", "tompkins", "ulster", "warren", "washington", "wayne", "westchester", "wyoming", "yates"},
            {"alamance", "alexander", "alleghany", "anson", "ashe", "avery", "beaufort", "bertie", "bladen", "brunswick", "buncombe", "burke", "cabarrus", "caldwell", "camden", "carteret", "caswell", "catawba", "chatham", "cherokee", "chowan", "clay", "cleveland", "columbus", "craven", "cumberland", "currituck", "dare", "davidson", "davie", "duplin", "durham", "edgecombe", "forsyth", "franklin", "gaston", "gates", "graham", "granville", "greene", "guilford", "halifax", "harnett", "haywood", "henderson", "hertford", "hoke", "hyde", "iredell", "jackson", "johnston", "jones", "lee", "lenoir", "lincoln", "mcdowell", "macon", "madison", "martin", "mecklenburg", "mitchell", "montgomery", "moore", "nash", "new hanover", "northampton", "onslow", "orange", "pamlico", "pasquotank", "pender", "perquimans", "person", "pitt", "polk", "randolph", "richmond", "robeson", "rockingham", "rowan", "rutherford", "sampson", "scotland", "stanly", "stokes", "surry", "swain", "transylvania", "tyrrell", "union", "vance", "wake", "warren", "washington", "watauga", "wayne", "wilkes", "wilson", "yadkin", "yancey"},
            {"adams", "barnes", "benson", "billings", "bottineau", "bowman", "burke", "burleigh", "cass", "cavalier", "dickey", "divide", "dunn", "eddy", "emmons", "foster", "golden valley", "grand forks", "grant", "griggs", "hettinger", "kidder", "lamoure", "logan", "mchenry", "mcintosh", "mckenzie", "mclean", "mercer", "morton", "mountrail", "nelson", "oliver", "pembina", "pierce", "ramsey", "ransom", "renville", "richland", "rolette", "sargent", "sheridan", "sioux", "slope", "stark", "steele", "stutsman", "towner", "traill", "walsh", "ward", "wells", "williams"},
            {"adams", "allen", "ashland", "ashtabula", "athens", "auglaize", "belmont", "brown", "butler", "carroll", "champaign", "clark", "clermont", "clinton", "columbiana", "coshocton", "crawford", "cuyahoga", "darke", "defiance", "delaware", "erie", "fairfield", "fayette", "franklin", "fulton", "gallia", "geauga", "greene", "guernsey", "hamilton", "hancock", "hardin", "harrison", "henry", "highland", "hocking", "holmes", "huron", "jackson", "jefferson", "knox", "lake", "lawrence", "licking", "logan", "lorain", "lucas", "madison", "mahoning", "marion", "medina", "meigs", "mercer", "miami", "monroe", "montgomery", "morgan", "morrow", "muskingum", "noble", "ottawa", "paulding", "perry", "pickaway", "pike", "portage", "preble", "putnam", "richland", "ross", "sandusky", "scioto", "seneca", "shelby", "stark", "summit", "trumbull", "tuscarawas", "union", "van wert", "vinton", "warren", "washington", "wayne", "williams", "wood", "wyandot"},
            {"adair", "alfalfa", "atoka", "beaver", "beckham", "blaine", "bryan", "caddo", "canadian", "carter", "cherokee", "choctaw", "cimarron", "cleveland", "coal", "comanche", "cotton", "craig", "creek", "custer", "delaware", "dewey", "ellis", "garfield", "garvin", "grady", "grant", "greer", "harmon", "harper", "haskell", "hughes", "jackson", "jefferson", "johnston", "kay", "kingfisher", "kiowa", "latimer", "le flore", "lincoln", "logan", "love", "mcclain", "mccurtain", "mcintosh", "major", "marshall", "mayes", "murray", "muskogee", "noble", "nowata", "okfuskee", "oklahoma", "okmulgee", "osage", "ottawa", "pawnee", "payne", "pittsburg", "pontotoc", "pottawatomie", "pushmataha", "roger mills", "rogers", "seminole", "sequoyah", "stephens", "texas", "tillman", "tulsa", "wagoner", "washington", "washita", "woods", "woodward"},
            {"baker", "benton", "clackamas", "clatsop", "columbia", "coos", "crook", "curry", "deschutes", "douglas", "gilliam", "grant", "harney", "hood river", "jackson", "jefferson", "josephine", "klamath", "lake", "lane", "lincoln", "linn", "malheur", "marion", "morrow", "multnomah", "polk", "sherman", "tillamook", "umatilla", "union", "wallowa", "wasco", "washington", "wheeler", "yamhill"},
            {"adams", "allegheny", "armstrong", "beaver", "bedford", "berks", "blair", "bradford", "bucks", "butler", "cambria", "cameron", "carbon", "centre", "chester", "clarion", "clearfield", "clinton", "columbia", "crawford", "cumberland", "dauphin", "delaware", "elk", "erie", "fayette", "forest", "franklin", "fulton", "greene", "huntingdon", "indiana", "jefferson", "juniata", "lackawanna", "lancaster", "lawrence", "lebanon", "lehigh", "luzerne", "lycoming", "mc kean", "mercer", "mifflin", "monroe", "montgomery", "montour", "northampton", "northumberland", "perry", "philadelphia", "pike", "potter", "schuylkill", "snyder", "somerset", "sullivan", "susquehanna", "tioga", "union", "venango", "warren", "washington", "wayne", "westmoreland", "wyoming", "york"},
            {"bristol", "kent", "newport", "providence", "washington"},
            {"abbeville", "aiken", "allendale", "anderson", "bamberg", "barnwell", "beaufort", "berkeley", "calhoun", "charleston", "cherokee", "chester", "chesterfield", "clarendon", "colleton", "darlington", "dillon", "dorchester", "edgefield", "fairfield", "florence", "georgetown", "greenville", "greenwood", "hampton", "horry", "jasper", "kershaw", "lancaster", "laurens", "lee", "lexington", "mccormick", "marion", "marlboro", "newberry", "oconee", "orangeburg", "pickens", "richland", "saluda", "spartanburg", "sumter", "union", "williamsburg", "york"},
            {"aurora", "beadle", "bennett", "bon homme", "brookings", "brown", "brule", "buffalo", "butte", "campbell", "charles mix", "clark", "clay", "codington", "corson", "custer", "davison", "day", "deuel", "dewey", "douglas", "edmunds", "fall river", "faulk", "grant", "gregory", "haakon", "hamlin", "hand", "hanson", "harding", "hughes", "hutchinson", "hyde", "jackson", "jerauld", "jones", "kingsbury", "lake", "lawrence", "lincoln", "lyman", "mccook", "mcpherson", "marshall", "meade", "mellette", "miner", "minnehaha", "moody", "pennington", "perkins", "potter", "roberts", "sanborn", "shannon", "spink", "stanley", "sully", "todd", "tripp", "turner", "union", "walworth", "yankton", "ziebach"},
            {"anderson", "bedford", "benton", "bledsoe", "blount", "bradley", "campbell", "cannon", "carroll", "carter", "cheatham", "chester", "claiborne", "clay", "cocke", "coffee", "crockett", "cumberland", "davidson", "decatur", "dekalb", "dickson", "dyer", "fayette", "fentress", "franklin", "gibson", "giles", "grainger", "greene", "grundy", "hamblen", "hamilton", "hancock", "hardeman", "hardin", "hawkins", "haywood", "henderson", "henry", "hickman", "houston", "humphreys", "jackson", "jefferson", "johnson", "knox", "lake", "lauderdale", "lawrence", "lewis", "lincoln", "loudon", "mcminn", "mcnairy", "macon", "madison", "marion", "marshall", "maury", "meigs", "monroe", "montgomery", "moore", "morgan", "obion", "overton", "perry", "pickett", "polk", "putnam", "rhea", "roane", "robertson", "rutherford", "scott", "sequatchie", "sevier", "shelby", "smith", "stewart", "sullivan", "sumner", "tipton", "trousdale", "unicoi", "union", "van buren", "warren", "washington", "wayne", "weakley", "white", "williamson", "wilson"},
            {"anderson", "andrews", "angelina", "aransas", "archer", "armstrong", "atascosa", "austin", "bailey", "bandera", "bastrop", "baylor", "bee", "bell", "bexar", "blanco", "borden", "bosque", "bowie", "brazoria", "brazos", "brewster", "briscoe", "brooks", "brown", "burleson", "burnet", "caldwell", "calhoun", "callahan", "cameron", "camp", "carson", "cass", "castro", "chambers", "cherokee", "childress", "clay", "cochran", "coke", "coleman", "collin", "collingsworth", "colorado", "comal", "comanche", "concho", "cooke", "coryell", "cottle", "crane", "crockett", "crosby", "culberson", "dallam", "dallas", "dawson", "deaf smith", "delta", "denton", "dewitt", "dickens", "dimmit", "donley", "duval", "eastland", "ector", "edwards", "ellis", "el paso", "erath", "falls", "fannin", "fayette", "fisher", "floyd", "foard", "fort bend", "franklin", "freestone", "frio", "gaines", "galveston", "garza", "gillespie", "glasscock", "goliad", "gonzales", "gray", "grayson", "gregg", "grimes", "guadalupe", "hale", "hall", "hamilton", "hansford", "hardeman", "hardin", "harris", "harrison", "hartley", "haskell", "hays", "hemphill", "henderson", "hidalgo", "hill", "hockley", "hood", "hopkins", "houston", "howard", "hudspeth", "hunt", "hutchinson", "irion", "jack", "jackson", "jasper", "jeff davis", "jefferson", "jim hogg", "jim wells", "johnson", "jones", "karnes", "kaufman", "kendall", "kenedy", "kent", "kerr", "kimble", "king", "kinney", "kleberg", "knox", "lamar", "lamb", "lampasas", "la salle", "lavaca", "lee", "leon", "liberty", "limestone", "lipscomb", "live oak", "llano", "loving", "lubbock", "lynn", "mcculloch", "mclennan", "mcmullen", "madison", "marion", "martin", "mason", "matagorda", "maverick", "medina", "menard", "midland", "milam", "mills", "mitchell", "montague", "montgomery", "moore", "morris", "motley", "nacogdoches", "navarro", "newton", "nolan", "nueces", "ochiltree", "oldham", "orange", "palo pinto", "panola", "parker", "parmer", "pecos", "polk", "potter", "presidio", "rains", "randall", "reagan", "real", "red river", "reeves", "refugio", "roberts", "robertson", "rockwall", "runnels", "rusk", "sabine", "san augustine", "san jacinto", "san patricio", "san saba", "schleicher", "scurry", "shackelford", "shelby", "sherman", "smith", "somervell", "starr", "stephens", "sterling", "stonewall", "sutton", "swisher", "tarrant", "taylor", "terrell", "terry", "throckmorton", "titus", "tom green", "travis", "trinity", "tyler", "upshur", "upton", "uvalde", "val verde", "van zandt", "victoria", "walker", "waller", "ward", "washington", "webb", "wharton", "wheeler", "wichita", "wilbarger", "willacy", "williamson", "wilson", "winkler", "wise", "wood", "yoakum", "young", "zapata", "zavala"},
            {"beaver", "box elder", "cache", "carbon", "daggett", "davis", "duchesne", "emery", "garfield", "grand", "iron", "juab", "kane", "millard", "morgan", "piute", "rich", "salt lake", "san juan", "sanpete", "sevier", "summit", "tooele", "uintah", "utah", "wasatch", "washington", "wayne", "weber"},
            {"addison", "bennington", "caledonia", "chittenden", "essex", "franklin", "grand isle", "lamoille", "orange", "orleans", "rutland", "washington", "windham", "windsor"},
            {"accomack", "albemarle", "alleghany", "amelia", "amherst", "appomattox", "arlington", "augusta", "bath", "bedford", "bland", "botetourt", "brunswick", "buchanan", "buckingham", "campbell", "caroline", "carroll", "charles city", "charlotte", "chesterfield", "clarke", "craig", "culpeper", "cumberland", "dickenson", "dinwiddie", "essex", "fairfax", "fauquier", "floyd", "fluvanna", "franklin", "frederick", "giles", "gloucester", "goochland", "grayson", "greene", "greensville", "halifax", "hanover", "henrico", "henry", "highland", "isle of wight", "james city", "king and queen", "king george", "king william", "lancaster", "lee", "loudoun", "louisa", "lunenburg", "madison", "mathews", "mecklenburg", "middlesex", "montgomery", "nelson", "new kent", "northampton", "northumberland", "nottoway", "orange", "page", "patrick", "pittsylvania", "powhatan", "prince edward", "prince george", "prince william", "pulaski", "rappahannock", "richmond", "roanoke", "rockbridge", "rockingham", "russell", "scott", "shenandoah", "smyth", "southampton", "spotsylvania", "stafford", "surry", "sussex", "tazewell", "warren", "washington", "westmoreland", "wise", "wythe", "york", "alexandria city", "bedford city", "bristol city", "buena vista city", "charlottesville city", "chesapeake city", "clifton forge city", "colonial heights city", "covington city", "danville city", "emporia city", "fairfax city", "falls church city", "franklin city", "fredericksburg city", "galax city", "hampton city", "harrisonburg city", "hopewell city", "lexington city", "lynchburg city", "manassas city", "manassas park city", "martinsville city", "newport news city", "norfolk city", "norton city", "petersburg city", "poquoson city", "portsmouth city", "radford city", "richmond city", "roanoke city", "salem city", "south boston city", "staunton city", "suffolk city", "virginia beach city", "waynesboro city", "williamsburg city", "winchester city"},
            {"adams", "asotin", "benton", "chelan", "clallam", "clark", "columbia", "cowlitz", "douglas", "ferry", "franklin", "garfield", "grant", "grays harbor", "island", "jefferson", "king", "kitsap", "kittitas", "klickitat", "lewis", "lincoln", "mason", "okanogan", "pacific", "pend oreille", "pierce", "san juan", "skagit", "skamania", "snohomish", "spokane", "stevens", "thurston", "wahkiakum", "walla walla", "whatcom", "whitman", "yakima"},
            {"barbour", "berkeley", "boone", "braxton", "brooke", "cabell", "calhoun", "clay", "doddridge", "fayette", "gilmer", "grant", "greenbrier", "hampshire", "hancock", "hardy", "harrison", "jackson", "jefferson", "kanawha", "lewis", "lincoln", "logan", "mcdowell", "marion", "marshall", "mason", "mercer", "mineral", "mingo", "monongalia", "monroe", "morgan", "nicholas", "ohio", "pendleton", "pleasants", "pocahontas", "preston", "putnam", "raleigh", "randolph", "ritchie", "roane", "summers", "taylor", "tucker", "tyler", "upshur", "wayne", "webster", "wetzel", "wirt", "wood", "wyoming"},
            {"adams", "ashland", "barron", "bayfield", "brown", "buffalo", "burnett", "calumet", "chippewa", "clark", "columbia", "crawford", "dane", "dodge", "door", "douglas", "dunn", "eau claire", "florence", "fond du lac", "forest", "grant", "green", "green lake", "iowa", "iron", "jackson", "jefferson", "juneau", "kenosha", "kewaunee", "la crosse", "lafayette", "langlade", "lincoln", "manitowoc", "marathon", "marinette", "marquette", "menominee", "milwaukee", "monroe", "oconto", "oneida", "outagamie", "ozaukee", "pepin", "pierce", "polk", "portage", "price", "racine", "richland", "rock", "rusk", "st. croix", "sauk", "sawyer", "shawano", "sheboygan", "taylor", "trempealeau", "vernon", "vilas", "walworth", "washburn", "washington", "waukesha", "waupaca", "waushara", "winnebago", "wood"},
            {"albany", "big horn", "campbell", "carbon", "converse", "crook", "fremont", "goshen", "hot springs", "johnson", "laramie", "lincoln", "natrona", "niobrara", "park", "platte", "sheridan", "sublette", "sweetwater", "teton", "uinta", "washakie", "weston", ""},
            {"aleutians east", "aleutians west", "anchorage", "bethel", "bristol bay", "denali", "dillingham", "fairbanks north star", "haines", "juneau", "kenai peninsula", "ketchikan gateway", "kodiak island", "lake and peninsula", "matanuska-susitna", "nome", "north slope", "northwest arctic", "prince of wales-outer ketchikan", "sitka", "skagway-yakutat-angoon", "skagway-hoonah-angoon", "southeast fairbanks", "valdez-cordova", "wade hampton", "wrangell-petersburg", "yakutat", "yukon-koyukuk"},
            {"hawaii", "honolulu", "kalawao", "kauai", "maui"},
        };

    @Override
    public void map(LongWritable key, Text value, Context context) 
        throws IOException, InterruptedException {
            
        String line[] = value.toString().split("\t"); // Input string to parse

        // Extract the columns of interest
        String year = line[0];
        String state = line[1];
        String county = line[2];
        String pop = line[3];
        String areo = line[4];
        String offense = line[5];
        
        // Given correct data format for this line
        if ((!state.equals("STATE")) && (Integer.parseInt(state) < 52) && (!pop.equals("0"))) // If valid state & valid line & valid population size (Non-NULL)
        {
            String newState; // Records State name as String, not index
            String newCounty;

            // List of States in order specified by data documentation
            String [] statesList = {"al", "az", "ar", "ca", "co", 
                    "ct", "dl", "dc", "fl", "ga", 
                    "id", "il", "in", "ia", "ks", 
                    "ky", "la", "me", "md", "ma",
                    "mi", "mn", "ms", "mo", "mt", 
                    "ne", "nv", "nh", "nj", "nm", 
                    "ny", "nc", "nd", "oh", "ok", 
                    "or", "pa", "ri", "sc", "sd", 
                    "tn", "tx", "ut", "vt", "va", 
                    "wa", "wv", "wi", "wy", "ak", "hi"};

            int offense_id = Integer.parseInt(offense.substring(0, 2));
            String off_out;
            if (offense_id < 5)
            {
                off_out = "1\t0\t0\t0";
            }
            else if (offense_id < 18)
            {
                off_out = "0\t1\t0\t0";
            }
            else if (offense_id == 18)
            {
                off_out = "0\t0\t1\t0";
            }
            else
            {
                off_out = "0\t0\t0\t1";
            }

            // Record the new state string
            try {
                newState = statesList[Integer.parseInt(state)-1];
                newCounty = countiesList[Integer.parseInt(state)-1][Integer.parseInt(county)-1];
                String out = year + "_" + newState + "_" + newCounty; // Generate and format the cleaned line
                String val = pop + "\t" + off_out;
            
                context.write(new Text(out), new Text(val)); // Write this line, the NullWritable allows us not to have any value with associated with the key
            }
            catch(Exception e) {
                //  Block of code to handle errors
            }
        }
    }
}